import type { Config } from "tailwindcss";

export default {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        primary: "#b3290f",
        "on-primary": "#ffffff",
        "primary-container": "#ff5f40",
        "on-primary-container": "#5f0a00",
        "primary-fixed": "#ffdad3",
        "primary-fixed-dim": "#ffb4a5",
        "on-primary-fixed": "#3e0400",
        "on-primary-fixed-variant": "#8e1500",
        secondary: "#785900",
        "on-secondary": "#ffffff",
        "secondary-container": "#fdc003",
        "on-secondary-container": "#6c5000",
        "secondary-fixed": "#ffdf9e",
        "secondary-fixed-dim": "#fabd00",
        "on-secondary-fixed": "#261a00",
        "on-secondary-fixed-variant": "#5b4300",
        tertiary: "#5f5e5e",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#969494",
        "on-tertiary-container": "#2d2d2d",
        "tertiary-fixed": "#e5e2e1",
        "tertiary-fixed-dim": "#c8c6c5",
        "on-tertiary-fixed": "#1c1b1b",
        "on-tertiary-fixed-variant": "#474746",
        surface: "#f9f9fe",
        "surface-dim": "#d9dade",
        "surface-bright": "#f9f9fe",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f3f8",
        "surface-container": "#ededf2",
        "surface-container-high": "#e8e8ed",
        "surface-container-highest": "#e2e2e7",
        "on-surface": "#1a1c1f",
        "on-surface-variant": "#5a413b",
        "inverse-surface": "#2e3034",
        "inverse-on-surface": "#f0f0f5",
        outline: "#8e706a",
        "outline-variant": "#e3beb7",
        "surface-tint": "#b3290f",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        background: "#f9f9fe",
        "on-background": "#1a1c1f",
        "surface-variant": "#e2e2e7",
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
      },
      fontFamily: {
        sans: ["PlusJakartaSans-Regular", "system-ui", "sans-serif"],
        "sans-bold": ["PlusJakartaSans-Bold", "system-ui", "sans-serif"],
        "sans-semibold": ["PlusJakartaSans-SemiBold", "system-ui", "sans-serif"],
        "sans-extrabold": ["PlusJakartaSans-ExtraBold", "system-ui", "sans-serif"],
        "sans-medium": ["PlusJakartaSans-Medium", "system-ui", "sans-serif"],
      },
      spacing: {
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "32px",
        gutter: "12px",
        "margin-mobile": "16px",
      },
      boxShadow: {
        card: "0 4px 20px rgba(0, 0, 0, 0.05)",
        "card-hover": "0 8px 30px rgba(0, 0, 0, 0.1)",
      },
    },
  },
  plugins: [],
} satisfies Config;
